name: scp files

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH2 }}
        port: ${{ secrets.PORT }}
        source: "index.html"
        target: "/home/ubuntu/"
    - name: executing remote ssh commands to cp files
      uses: appleboy/ssh-action@v0.1.6
      with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
               sudo cp -R /home/ubuntu/index.html /var/www/html/
               sudo chown -R www-data:www-data /var/www/html/index.html
               sudo systemctl restart apache2.service
